DELETE http://localhost:3003/api/blogs/64369e6d060411bbc9dc7223
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0MzkzNzU3ODljY2ZkMmUzYjNmMzM3YyIsImlhdCI6MTY4MTQ3MTM1OH0.ZfxIqTrcpTJEv7xeT0lLh7NvwAfZRkiWRulFsUmRIic

